### ISSUE TITLE
Service fails to start

### ISSUE THREAD

**Issue by adamburt** [bmartin5692/ScriptResultCurator#15]
Service fails to start on WIndows Server 2012. No error logs in the eventvwr.

![image](https://cloud.githubusercontent.com/assets/9579204/18026609/deea58d6-6c44-11e6-8548-7543ef63ef3d.png)

**Comment by bmartin5692** [comment]
Could be related to #14 .

I just updated the Service start code to use a threadpool to start now. Could you try the latest 1.2.2.2 installer I just posted? It will require you uninstall the previous version first.

Additionally, before starting the service enable Debug logs.

**Comment by bmartin5692** [comment]
Result of a bad configuration file. Closing.
